// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/miiy/goc/auth"
	"github.com/miiy/goc/auth/jwt"
	"github.com/miiy/goc/contrib/sdk/wechat/miniprogram"
	"github.com/miiy/goc/db"
	"github.com/miiy/goc/examples/apiserver/app"
	"github.com/miiy/goc/examples/apiserver/config"
	"github.com/miiy/goc/logger"
	"github.com/miiy/goc/redis"
	"github.com/miiy/goc/service/auth/repository"
	"github.com/miiy/goc/service/auth/server"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initApp(conf string) (*app.App, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	dbConfig := providerDBConfig(configConfig)
	v := providerDBOption(configConfig)
	dbDB, err := db.NewDB(dbConfig, v...)
	if err != nil {
		return nil, nil, err
	}
	options := providerRedisOptions(configConfig)
	universalClient, err := redis.NewRedis(options)
	if err != nil {
		return nil, nil, err
	}
	v2 := providerLoggerOption()
	loggerLogger, err := logger.NewLogger(v2...)
	if err != nil {
		return nil, nil, err
	}
	jwtOptions := providerJwtAuthOptions(configConfig)
	jwtAuth := jwt.NewJWTAuth(jwtOptions)
	gormDB := providerGorm(dbDB)
	authRepository := repository.NewAuthRepository(gormDB)
	authTokenRepository := repository.NewRedisRepository(universalClient)
	miniProgram, err := providerMiniProgram(configConfig)
	if err != nil {
		return nil, nil, err
	}
	authServiceServer := server.NewAuthServiceServer(authRepository, authTokenRepository, jwtAuth, miniProgram)
	appApp := app.NewApp(configConfig, dbDB, universalClient, loggerLogger, jwtAuth, authServiceServer)
	return appApp, func() {
	}, nil
}

// wire.go:

func providerLoggerOption() []logger.Option {
	return nil
}

func providerDBConfig(config2 *config.Config) db.Config {
	return db.Config{
		Driver:   config2.Database.Driver,
		Host:     config2.Database.Host,
		Port:     config2.Database.Port,
		Username: config2.Database.Username,
		Password: config2.Database.Password,
		Database: config2.Database.Database,
	}
}

func providerDBOption(config2 *config.Config) []db.Option {
	return nil
}

func providerRedisOptions(config2 *config.Config) *redis.Options {
	return &redis.Options{
		Addrs:    config2.Redis.Addrs,
		Password: config2.Redis.Password,
		DB:       config2.Redis.DB,
	}
}

func providerGorm(db2 *db.DB) *gorm.DB {
	return db2.Gorm()
}

func providerJwtAuthOptions(config2 *config.Config) *jwt.Options {
	return &jwt.Options{
		Secret:    config2.Jwt.Secret,
		Issuer:    config2.Jwt.Issuer,
		ExpiresIn: config2.Jwt.ExpiresIn,
	}
}

func providerMiniProgram(config2 *config.Config) (*miniprogram.MiniProgram, error) {
	return nil, nil
}

func providerUser(authRepository repository.AuthRepository) auth.UserProvider {
	return authRepository
}
