app:
  name: goc
  env: local # local, testing, production
  debug: true
  version: 1.0
database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: goc
  username: root
  password: 123456
redis:
  addrs:
    - 127.0.0.1:6379
  username:
  password:
  db: 0
server:
  http:
    addr: 0.0.0.0:8080
    url:
  grpc:
    addr: 0.0.0.0:50051
    tls:
      certFile: ./configs/x509/server_cert.pem
      keyFile: ./configs/x509/server_key.pem
      caFile: ./configs/x509/ca_cert.pem
grpcClient:
  endpoint: 127.0.0.1:50051
  tls:
    serverName: "*.goc.dev"
    certFile: ./configs/x509/client_cert.pem
    keyFile: ./configs/x509/client_key.pem
    caFile: ./configs/x509/ca_cert.pem
jwt:
  secret: 123456
  expiresIn: 7200 # second 7200s = 2h
snowflake:
  node: 1
