// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/miiy/goc/auth/jwt"
	"github.com/miiy/goc/db"
	"github.com/miiy/goc/examples/apiserver/config"
	"github.com/miiy/goc/logger"
	"github.com/miiy/goc/redis"
	"github.com/miiy/goc/service/auth/repository"
	"github.com/miiy/goc/service/auth/server"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApp(conf string) (*App, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	dbConfig := providerDatabase(configConfig)
	v := providerDatabaseOption(configConfig)
	database, err := db.NewDatabase(dbConfig, v...)
	if err != nil {
		return nil, nil, err
	}
	options := providerRedisOptions(configConfig)
	universalClient, err := redis.NewRedis(options)
	if err != nil {
		return nil, nil, err
	}
	v2 := providerLoggerOption(configConfig)
	loggerLogger, err := logger.NewLogger(v2...)
	if err != nil {
		return nil, nil, err
	}
	jwtOptions := providerJwtAuthOptions(configConfig)
	jwtAuth := jwt.NewJWTAuth(jwtOptions)
	gormDB := providerGorm(database)
	authRepository := repository.NewAuthRepository(gormDB)
	authTokenRepository := repository.NewRedisRepository(universalClient)
	authServiceServer := server.NewAuthServiceServer(authRepository, authTokenRepository, jwtAuth)
	appApp := NewApp(configConfig, database, universalClient, loggerLogger, jwtAuth, authServiceServer)
	return appApp, func() {
	}, nil
}

// wire.go:

func providerGorm(db2 *db.Database) *gorm.DB {
	return db2.Gorm
}

func providerRedisOptions(config2 *config.Config) *redis.Options {
	return &redis.Options{
		Addrs:    config2.Redis.Addrs,
		Password: config2.Redis.Password,
		DB:       config2.Redis.DB,
	}
}

func providerJwtAuthOptions(config2 *config.Config) *jwt.Options {
	return &jwt.Options{
		Secret:    config2.Jwt.Secret,
		Issuer:    config2.Jwt.Issuer,
		ExpiresIn: config2.Jwt.ExpiresIn,
	}
}

func providerLoggerOption(config2 *config.Config) []logger.Option {
	return []logger.Option{}
}

func providerDatabase(config2 *config.Config) db.Config {
	return db.Config{
		Driver:   config2.Database.Driver,
		Host:     config2.Database.Host,
		Port:     config2.Database.Port,
		Username: config2.Database.Username,
		Password: config2.Database.Password,
		Database: config2.Database.Database,
	}
}

func providerDatabaseOption(config2 *config.Config) []db.Option {
	return []db.Option{}
}
