// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: examples/apiserver/api/echo/v1/echo.proto

package echov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Echo_EchoGet_FullMethodName     = "/goc.examples.api.echo.v1.Echo/EchoGet"
	Echo_EchoQueryId_FullMethodName = "/goc.examples.api.echo.v1.Echo/EchoQueryId"
	Echo_EchoPost_FullMethodName    = "/goc.examples.api.echo.v1.Echo/EchoPost"
	Echo_EchoError_FullMethodName   = "/goc.examples.api.echo.v1.Echo/EchoError"
)

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	EchoGet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Message, error)
	EchoQueryId(ctx context.Context, in *EchoQueryIdRequest, opts ...grpc.CallOption) (*Message, error)
	EchoPost(ctx context.Context, in *EchoPostRequest, opts ...grpc.CallOption) (*Message, error)
	EchoError(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Message, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) EchoGet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, Echo_EchoGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoQueryId(ctx context.Context, in *EchoQueryIdRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, Echo_EchoQueryId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoPost(ctx context.Context, in *EchoPostRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, Echo_EchoPost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoError(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, Echo_EchoError_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility
type EchoServer interface {
	EchoGet(context.Context, *emptypb.Empty) (*Message, error)
	EchoQueryId(context.Context, *EchoQueryIdRequest) (*Message, error)
	EchoPost(context.Context, *EchoPostRequest) (*Message, error)
	EchoError(context.Context, *emptypb.Empty) (*Message, error)
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (UnimplementedEchoServer) EchoGet(context.Context, *emptypb.Empty) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoGet not implemented")
}
func (UnimplementedEchoServer) EchoQueryId(context.Context, *EchoQueryIdRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoQueryId not implemented")
}
func (UnimplementedEchoServer) EchoPost(context.Context, *EchoPostRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoPost not implemented")
}
func (UnimplementedEchoServer) EchoError(context.Context, *emptypb.Empty) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoError not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_EchoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoGet(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoQueryId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoQueryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoQueryId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoQueryId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoQueryId(ctx, req.(*EchoQueryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoPost(ctx, req.(*EchoPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoError(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goc.examples.api.echo.v1.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EchoGet",
			Handler:    _Echo_EchoGet_Handler,
		},
		{
			MethodName: "EchoQueryId",
			Handler:    _Echo_EchoQueryId_Handler,
		},
		{
			MethodName: "EchoPost",
			Handler:    _Echo_EchoPost_Handler,
		},
		{
			MethodName: "EchoError",
			Handler:    _Echo_EchoError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/apiserver/api/echo/v1/echo.proto",
}
