// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: examples/apiserver/api/echo/v1/echo.proto

package echov1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MessageMultiError, or nil if none found.
func (m *Message) ValidateAll() error {
	return m.validate(true)
}

func (m *Message) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserName

	// no validation rules for Message

	if len(errors) > 0 {
		return MessageMultiError(errors)
	}

	return nil
}

// MessageMultiError is an error wrapping multiple validation errors returned
// by Message.ValidateAll() if the designated constraints aren't met.
type MessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageMultiError) AllErrors() []error { return m }

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on EchoQueryIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EchoQueryIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EchoQueryIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EchoQueryIdRequestMultiError, or nil if none found.
func (m *EchoQueryIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EchoQueryIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return EchoQueryIdRequestMultiError(errors)
	}

	return nil
}

// EchoQueryIdRequestMultiError is an error wrapping multiple validation errors
// returned by EchoQueryIdRequest.ValidateAll() if the designated constraints
// aren't met.
type EchoQueryIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EchoQueryIdRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EchoQueryIdRequestMultiError) AllErrors() []error { return m }

// EchoQueryIdRequestValidationError is the validation error returned by
// EchoQueryIdRequest.Validate if the designated constraints aren't met.
type EchoQueryIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EchoQueryIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EchoQueryIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EchoQueryIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EchoQueryIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EchoQueryIdRequestValidationError) ErrorName() string {
	return "EchoQueryIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EchoQueryIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEchoQueryIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EchoQueryIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EchoQueryIdRequestValidationError{}

// Validate checks the field values on EchoPostRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EchoPostRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EchoPostRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EchoPostRequestMultiError, or nil if none found.
func (m *EchoPostRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EchoPostRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserName

	if len(errors) > 0 {
		return EchoPostRequestMultiError(errors)
	}

	return nil
}

// EchoPostRequestMultiError is an error wrapping multiple validation errors
// returned by EchoPostRequest.ValidateAll() if the designated constraints
// aren't met.
type EchoPostRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EchoPostRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EchoPostRequestMultiError) AllErrors() []error { return m }

// EchoPostRequestValidationError is the validation error returned by
// EchoPostRequest.Validate if the designated constraints aren't met.
type EchoPostRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EchoPostRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EchoPostRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EchoPostRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EchoPostRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EchoPostRequestValidationError) ErrorName() string { return "EchoPostRequestValidationError" }

// Error satisfies the builtin error interface
func (e EchoPostRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEchoPostRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EchoPostRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EchoPostRequestValidationError{}
